// Login
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const GET_VALID_TOKEN = 'GET_VALID_TOKEN';
export const TOKEN_CHECK_DONE = 'TOKEN_CHECK_DONE'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

//Accounts
export const FETCH_ACCOUNTS_START = 'FETCH_ACCOUNTS_START';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAIL = 'FETCH_ACCOUNTS_FAIL';
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const ADD_ACCOUNT_START = 'ADD_ACCOUNT_START';
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';
export const ADD_ACCOUNT_FAIL = 'ADD_ACCOUNT_FAIL';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const ADD_ACCOUNT_RESET = 'ADD_ACCOUNT_RESET';
export const SEARCH_ACCOUNTS_SUCCESS = 'SEARCH_ACCOUNTS_SUCCESS';
export const SEARCH_ACCOUNTS = 'SEARCH_ACCOUNTS';
export const FILTER_ACCOUNTS_SUCCESS = 'FILTER_ACCOUNTS_SUCCESS';
export const FILTER_ACCOUNTS = 'FILTER_ACCOUNTS';
export const GET_A_USER = 'GET_A_USER'
export const GET_A_USER_START = 'GET_A_USER_START'
export const GET_A_USER_SUCCESS = 'GET_A_USER_SUCCESS'
export const GET_A_USER_FAIL = 'GET_A_USER_FAIL'

//INSTITUTION
export const INSTITUTION_CREATE = 'INSTITUTION_CREATE'
export const INSTITUTION_CREATE_START = 'INSTITUTION_CREATE_START'
export const INSTITUTION_CREATE_SUCCESS = 'INSTITUTION_CREATE_SUCCESS'
export const INSTITUTION_CREATE_FAIL = 'INSTITUTION_CREATE_FAIL'
export const INSTITUTION_GET_ALl = 'INSTITUTION_GET_ALl'
export const INSTITUTION_GET_ALl_START = 'INSTITUTION_GET_ALl_START'
export const INSTITUTION_GET_ALl_SUCCESS = 'INSTITUTION_GET_ALl_SUCCESS'
export const INSTITUTION_GET_ALl_FAIL = 'INSTITUTION_GET_ALl_FAIL'
export const INSTITUTION_CREATE_RESET = 'INSTITUTION_CREATE_RESET'

//COURSE
export const GET_ALL_COURSE = 'GET_ALL_COURSE'
export const GET_ALL_COURSE_START = 'GET_ALL_COURSE_START'
export const GET_ALL_COURSE_SUCCESS = 'GET_ALL_COURSE_SUCCESS'
export const GET_ALL_COURSE_FAIL = 'GET_ALL_COURSE_FAIL'

export const GET_A_COURSE = 'GET_A_COURSE'
export const GET_A_COURSE_START = 'GET_A_COURSE_START'
export const GET_A_COURSE_SUCCESS = 'GET_A_COURSE_SUCCESS'
export const GET_A_COURSE_FAIL = 'GET_A_COURSE_FAIL'

//LEARNING-OUTCOME
export const GET_ALL_LEARNING_OUTCOME = 'GET_ALL_LEARNING_OUTCOME'
export const GET_ALL_LEARNING_OUTCOME_START = 'GET_ALL_LEARNING_OUTCOME_START'
export const GET_ALL_LEARNING_OUTCOME_SUCCESS = 'GET_ALL_LEARNING_OUTCOME_SUCCESS'
export const GET_ALL_LEARNING_OUTCOME_FAIL = 'GET_ALL_LEARNING_OUTCOME_FAIL'

//LEARNING-OUTCOME-TITLE
export const GET_ALL_LEARNING_OUTCOME_TITLE = 'GET_ALL_LEARNING_OUTCOME_TITLE'
export const GET_ALL_LEARNING_OUTCOME_TITLE_START = 'GET_ALL_LEARNING_OUTCOME_TITLE_START'
export const GET_ALL_LEARNING_OUTCOME_TITLE_SUCCESS = 'GET_ALL_LEARNING_OUTCOME_TITLE_SUCCESS'
export const GET_ALL_LEARNING_OUTCOME_TITLE_FAIL = 'GET_ALL_LEARNING_OUTCOME_TITLE_FAIL'

//DOCUMENT
export const GET_ALL_DOCUMENT = 'GET_ALL_DOCUMENT'
export const GET_ALL_DOCUMENT_START = 'GET_ALL_DOCUMENT_START'
export const GET_ALL_DOCUMENT_SUCCESS = 'GET_ALL_DOCUMENT_SUCCESS'
export const GET_ALL_DOCUMENT_FAIL = 'GET_ALL_DOCUMENT_FAIL'

//DETAIL USER
export const GET_DETAIL_USER = 'GET_DETAIL_USER'
export const GET_DETAIL_USER_START = 'GET_DETAIL_USER_START'
export const GET_DETAIL_USER_SUCCESS = 'GET_DETAIL_USER_SUCCESS'
export const GET_DETAIL_USER_FAIL = 'GET_DETAIL_USER_FAIL'

//MAJOR
export const GET_ALL_MAJOR = 'GET_ALL_MAJOR'
export const GET_ALL_MAJOR_START = 'GET_ALL_MAJOR_START'
export const GET_ALL_MAJOR_SUCCESS = 'GET_ALL_MAJOR_SUCCESS'
export const GET_ALL_MAJOR_FAIL = 'GET_ALL_MAJOR_FAIL'

//TRAINING PROGRAMS
export const GET_ALL_TRAINING_PROGRAMS = 'GET_ALL_TRAINING_PROGRAMS'
export const GET_ALL_TRAINING_PROGRAMS_START = 'GET_ALL_TRAINING_PROGRAMS_START'
export const GET_ALL_TRAINING_PROGRAMS_SUCCESS = 'GET_ALL_TRAINING_PROGRAMS_SUCCESS'
export const GET_ALL_TRAINING_PROGRAMS_FAIL = 'GET_ALL_TRAINING_PROGRAMS_FAIL'
export const GET_A_TRAINING_PROGRAMS = 'GET_A_TRAINING_PROGRAMS'
export const GET_A_TRAINING_PROGRAMS_START = 'GET_A_TRAINING_PROGRAMS_START'
export const GET_A_TRAINING_PROGRAMS_SUCCESS = 'GET_A_TRAINING_PROGRAMS_SUCCESS'
export const GET_A_TRAINING_PROGRAMS_FAIL = 'GET_A_TRAINING_PROGRAMS_FAIL'

export const GET_LOC_OF_TRAINING = 'GET_LOC_OF_TRAINING'
export const GET_LOC_OF_TRAINING_START = 'GET_LOC_OF_TRAINING_START'
export const GET_LOC_OF_TRAINING_SUCCESS = 'GET_LOC_OF_TRAINING_SUCCESS'
export const GET_LOC_OF_TRAINING_FAIL = 'GET_LOC_OF_TRAINING_FAIL'
export const GET_COURSE_OF_TRAINING = 'GET_COURSE_OF_TRAINING'
export const GET_COURSE_OF_TRAINING_START = 'GET_COURSE_OF_TRAINING_START'
export const GET_COURSE_OF_TRAINING_SUCCESS = 'GET_COURSE_TRAINING_SUCCESS'
export const GET_COURSE_OF_TRAINING_FAIL = 'GET_COURSE_OF_TRAINING_FAIL'

//TRAINING TYPE
export const GET_ALL_TRAINING_TYPE = 'GET_ALL_TRAINING_TYPE'
export const GET_ALL_TRAINING_TYPE_START = 'GET_ALL_TRAINING_TYPE_START'
export const GET_ALL_TRAINING_TYPE_SUCCESS = 'GET_ALL_TRAINING_TYPE_SUCCESS'
export const GET_ALL_TRAINING_TYPE_FAIL = 'GET_ALL_TRAINING_TYPE_FAIL'

//COURSE CLASS
export const GET_ALL_COURSE_CLASS = 'GET_ALL_COURSE_CLASS'
export const GET_ALL_COURSE_CLASS_START = 'GET_ALL_COURSE_CLASS_START'
export const GET_ALL_COURSE_CLASS_SUCCESS = 'GET_ALL_COURSE_CLASS_SUCCESS'
export const GET_ALL_COURSE_CLASS_FAIL = 'GET_ALL_COURSE_CLASS_FAIL'

//COURSE YEAR
export const GET_ALL_COURSE_YEAR = 'GET_ALL_COURSE_YEAR'
export const GET_ALL_COURSE_YEAR_START = 'GET_ALL_COURSE_YEAR_START'
export const GET_ALL_COURSE_YEAR_SUCCESS = 'GET_ALL_COURSE_YEAR_SUCCESS'
export const GET_ALL_COURSE_YEAR_FAIL = 'GET_ALL_COURSE_YEAR_FAIL'

//NOTIFICATION
export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION"
export const GET_ALL_NOTIFICATION_SUCCESS = "GET_ALL_NOTIFICATION_SUCCESS"
export const GET_ALL_NOTIFICATION_START = "GET_ALL_NOTIFICATION_START"
export const GET_ALL_NOTIFICATION_FAIL = "GET_ALL_NOTIFICATION_FAIL"
